buildscript {
    def safeExtGet(prop, fallback) {
        rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
    }

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:${safeExtGet('androidGradlePluginVersion', '7.4.2')}")
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        
        maven {
            url 'https://repo.spring.io/plugins-release/'
            name 'Spring Plugins'
        }
    }
}


ext {
    reactNativeLibVersion = safeExtGet('reactNativeVersion', '+')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}